    version: '3'
    services:
        #postgres container
        postgres:
            image: postgres
            environment:
                - POSTGRES_USERNAME=postgres
                - POSTGRES_PASSWORD=postgres_password
                - POSTGRES_DB=simple_blog_api
        #API server container
        api:
            depends_on: 
                - postgres
            image: shanmugapriyar/simple_blog_api_ts-master
            restart: always
            build:
                context: .
                dockerfile: Dockerfile.dev
            volumes:
                - /usr/app/node_modules
                - ./:/usr/app
            environment:
                - POSTGRES_USERNAME=postgres
                - POSTGRES_HOST=postgres
                - POSTGRES_DB=simple_blog_api
                - POSTGRES_PASSWORD=postgres_password
                - POSTGRES_PORT=5432
            ports:
                - "3000:3000"